# Generated by Django 4.0.8 on 2026-09-13 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dianpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jianjie', models.TextField()),
                ('sales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage', models.IntegerField()),
                ('categlory', models.CharField(max_length=12)),
                ('xinghao', models.CharField(default='', max_length=100)),
                ('jiekou', models.CharField(default='', max_length=100)),
                ('dpi', models.CharField(default='', max_length=50)),
                ('light', models.CharField(default='', max_length=100)),
                ('use', models.CharField(default='', max_length=100)),
                ('introduce', models.TextField(default='')),
                ('dianpu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.dianpu')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.CharField(default='/media/avatar/img.png', max_length=200)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('pay_pwd', models.CharField(default='123456', max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('state', models.CharField(default='未付款', max_length=10)),
                ('code', models.CharField(default='', max_length=50)),
                ('t', models.CharField(default='1789216995.2113376', max_length=50)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=50)),
                ('text', models.TextField(blank=True, default='')),
                ('img1', models.TextField(blank=True, default='')),
                ('img2', models.TextField(blank=True, default='')),
                ('img3', models.TextField(blank=True, default='')),
                ('img4', models.TextField(blank=True, default='')),
                ('img5', models.TextField(blank=True, default='')),
                ('img6', models.TextField(blank=True, default='')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
