# Generated by Django 4.0.8 on 2026-09-13 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20260913_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=50)),
                ('text', models.TextField(blank=True, default='')),
                ('img1', models.TextField(blank=True, default='')),
                ('img2', models.TextField(blank=True, default='')),
                ('img3', models.TextField(blank=True, default='')),
                ('img4', models.TextField(blank=True, default='')),
                ('img5', models.TextField(blank=True, default='')),
                ('img6', models.TextField(blank=True, default='')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
