"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=um4hp$^n*_(jkv!uwatkl&4s1piz#ag=sn2$_$w&(@4(6&5$h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

ALIPAY_APPID="9021000168610790"
ALIPAY_GATEWAY="https://openapi-sandbox.dl.alipaydev.com/gateway.do"
ALIPAY_PRIVATE_KEY = """
-----BEGIN RSA PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCPpTFZzJeZipTalzNXQPTleYUnf+icvxSy+UgHmUy7ZHIDTGwzCjyU1Dmt/Gp6mEqX4TOnEXYwpJ9a3iX7k/g3RPDMbfeq2puT29rXB//FukEWY0y/dkUUGs79dKRWnpcw6enU1/FAlqduRjdsy6kqVzw7llZY5g4hbscOK8Ou2b8Dxf8fq7ALPk/rfM2DHhhixvWOSQf2Wc1FAAn+FDkDE993nCeLKn4YjPDLjQQJ3bAU2wEJgvfWNMHdMNHAH54DFJn9HURJbl4pt/5TSEHWMU9gdzfDuxQiVmGL03rsn4e4nv6UPzREKVT+DzeIjaDGqcYxxNB8YOAxwZFa1zAgMBAAECggEAMtHMvepmEAo5U4R+w3XVroHpm+niz+HCXvdWhmmz/fAxbf1RolUSzcyvg2B0A19xtH4WGhtRZzA2uJ0zbugQvu0DDDAzmRyyQgNcTwsjcD7O3C7RbkNXeR9q77yej46YCtQWyBiF38XtAlSRM0pyVOp8AtDTR6xMf4ODpP3Swz74KcpcIzfTDlxLJJCiEPJWeoGUfBRa/mAHqIL04Ayh8bF/QIBlZkj5Kfu2fwyPon63LLrWKC0x8rv34gLUZqtnfKyjXbt2xBRrbwBUcokxXJ4CpFmOZCsuBYXvr3SH1UPoivRzLbE6nVy6E6WenxP307pY8sr5R2QLphFs35oKYQKBgQDl6hfA9yFXsNHWPz6Ujt/gwliLSJW7rKpS95j6AbJFmnUxEQmzMD4sUjs7fmemLejO/HdEeDQnnzVj4bFXzC4qeaLommixxV6FpRzPAU6z9AcSOOExcU7BXcttl1BWaLct7h+XHyixQ0FLwiUcmInhhFVQHblh2tgkVfra1vm8ywKBgQCf8WWSHrEvUoDc22QnI2gGgaA4yiQEKLSOadDSQTfzS27oJVhKdSF0nCeGlsGzoyKMkgTLhzkxgpuz8vG5wRFWH1ZaxlTct6e2CCcrqsWNM3TzkozrKe3Pz98YYCOUDh+f9YDGuB/3euovoY/qLKnQKxgxHdVAb/aU6O7C9VGk+QKBgQCMcwONwqogqoiVK89r6xfCcpaqh23I1wK5aj2ORCkGMgPzNGhLiWYBpz496ssgjh0RDNNDBXc2RhBaubuLnHpSqMFGwZnyp0iYSoHHtJYRfNn401V6dTldQnHac8O6is0qKmtpMA0AVTLFc+b92cLV87SAUZ1C75L/CYhN4AaHwKBgF0tAPHt5WTfGGkRejf+vWRE8bUDtZWirQTmChvimJiokjS1RMkjkVjge3pBqxheagsgKaDz5tK79r8PQdjn65STbvg04E0wxIgcGc2rj6ihmHkpH+UDqSHORHZr0242CCBkoh+iNiUzOuiCo1dVq5u070P10DzYvPqk9CspROXpAoGBAMviuDXcqjNvjsooTUdzisaPTD1pECkFtBrOSWMz1b3TTmQ5evZQASIngl2JENRjWCQg+orcYd8bAFMeDpXxkgv62FrDCzP6VXL2GIWx1emv1Job1V45+C/cSqbempgnIR60Q6JgVZ4FEo+kGQUTCBfCqV39rjvWJqixbQ4Z7Qn
-----END RSA PRIVATE KEY-----
"""
ALIPAY_PUBLIC_KEY = """
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmkT7BmHTGwldOZtzLqtMb9YB9rMpLUHJwU9DLgodJ6YoTwRu3h9n7lfJWAgBC6HXsw+FS3FRx2kmCCnwRCe9rdNmgRxxPW+TX3/uFrLH9v6GQeT39lnmAkDL1wq/sqiqkaY3u+HoUREJXfv8AywE8xSS/4CXKDUrnDN6Ri1xXsLj9ZVCtL6XrFl/QghLP6DFwfKDwpeNU8XuPZqtfzUItcQrZ4JxiuUhs56Foe6cKPW0JdP0DEg7UTnaHIhvugRolXReRECht+UCB/jO6SxaytMghzeBeoKFzlm8sNdLoAW7vgcHbfne2Xc3pRWv0ytdbThbHCalv3+b0+yRMmn0wIDAQAB
-----END PUBLIC KEY-----
"""
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
SIMPLE_JWT={
    "ACCESS_TOKEN_LIFETIME":timedelta(minutes=5)
}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'iii',        # 你的数据库名称（必须提前在mysql创建好！）
        'USER': 'root',             # mysql用户名
        'PASSWORD': '13643929221Li.',       # mysql密码
        'HOST': '127.0.0.1',        # 本地数据库
        'PORT': '3306',             # mysql默认端口
        'OPTIONS': {
            'charset': 'utf8mb4'    # 支持表情符号
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES":[
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ]
}
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 465
EMAIL_USE_TLS=True
EMAIL_HOST_USER = '3163981881@qq.com'
EMAIL_HOST_PASSWORD = 'qcfhiaywwgpxdgja'
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR/"media"
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DEBUG = True
CORS_ALLOW_ALL_ORIGINS=True
STATIC_ROOT = BASE_DIR / "staticfiles"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
